export const TYPES = {
  EventBus: Symbol("EventBus"),
  UnitOfWork: Symbol("UnitOfWork"),
  UserRepository: Symbol("UserRepository"),
  CreateUserUseCase: Symbol("CreateUserAccountUseCase"),
  CreateServiceTokenUseCase: Symbol("CreateServiceTokenUseCase"),
  CreateUserMembershipService: Symbol("CreateUserMembershipService"),
  UserPersistenceMapper: Symbol("UserPersistenceMapper"),
  OrganizationRepository: Symbol("OrganizationRepository"),
  EnterpriseRepository: Symbol("EnterpriseRepository"),
  ApplicationRepository: Symbol("ApplicationRepository"),
  RoleRepository: Symbol("RoleRepository"),
  PermissionRepository: Symbol("PermissionRepository"),
  SessionRepository: Symbol("SessionRepository"),
  ServiceTokenRepository: Symbol("ServiceTokenRepository"),
  OAuthClientRepository: Symbol("OAuthClientRepository"),
  EmailVerificationRepository: Symbol("EmailVerificationRepository"),
  PasswordResetRepository: Symbol("PasswordResetRepository"),
  FrontendUrl: Symbol("FrontendUrl"),
  PublicUrl: Symbol("PublicUrl"),
  EncodingSecret: Symbol("EncodingSecret"),
  JWTSecret: Symbol("JWTSecret"),
  AuthProvider: Symbol("AuthProvider"),
  TokenProvider: Symbol("TokenProvider"),
  CreateEmailVerificationService: Symbol("CreateEmailVerificationService"),
  CheckUserOrganizationService: Symbol("CheckUserOrganizationService"),
  VerifyUserMembershipService: Symbol("VerifyUserMembershipService"),
  CreatePasswordResetService: Symbol("CreatePasswordResetService"),
  UserCreatedEventHandler: Symbol("UserCreatedEventHandler"),
  EmailVerifiedEventHandler: Symbol("EmailVerifiedEventHandler"),
  EnterpriseCreatedEventHandler: Symbol("EnterpriseCreatedEventHandler"),
  AutoVerifyEmail: Symbol("AutoVerifyEmail"),
  IdentityApplicationId: Symbol("IdentityApplicationId"),
  IdentityUrl: Symbol("IdentityUrl"),
  CreateUserService: Symbol("CreateUserService"),
  FindPersonalOrganizationService: Symbol("FindPersonalOrganizationService"),
  CompareEmailAddressesService: Symbol("CompareEmailAddressesService"),
  CreateServiceTokenService: Symbol("CreateServiceTokenService"),
  CreateOAuthClientService: Symbol("CreateOAuthClientService"),
  InviteRepository: Symbol("InviteRepository"),
  EmailAddressRepository: Symbol("EmailAddressRepository"),
  CodeChallengeRepository: Symbol("CodeChallengeRepository"),
  CreateOrganizationService: Symbol("CreateOrganizationService"),
  CreateEnterpriseService: Symbol("CreateEnterpriseService"),
  DeactivateServiceTokenService: Symbol("DeactivateServiceTokenService"),
  CreateCodeChallengeService: Symbol("CreateCodeChallengeService"),
  VerifyCodeChallengeService: Symbol("VerifyCodeChallengeService"),
  CreatePersonalOrganizationService: Symbol(
    "CreatePersonalOrganizationService",
  ),
  V4MarketingServiceTokenCreatedEventHandler: Symbol(
    "V4MarketingServiceTokenCreatedEventHandler",
  ),
  LegacyUserMigrationDispatchedEventHandler: Symbol(
    "LegacyUserMigrationDispatchedEventHandler",
  ),
  LegacyOrganizationMigrationDispatchedEventHandler: Symbol(
    "LegacyOrganizationMigrationDispatchedEventHandler",
  ),
  V4MarketingOrganizationMigrationDispatchedEventHandler: Symbol(
    "V4MarketingOrganizationMigrationDispatchedEventHandler",
  ),
  V4MarketingServiceTokenDeactivatedEventHandler: Symbol(
    "V4MarketingServiceTokenDeactivatedEventHandler",
  ),
  LegacyMembershipMigrationDispatchedEventHandler: Symbol(
    "LegacyMembershipMigrationDispatchedEventHandler",
  ),
  RequireSystemAdminService: Symbol("RequireSystemAdminService"),
  MktlabApplicationId: Symbol("MktlabApplicationId"),
  EmployeeInvitedEventHandler: Symbol("EmployeeInvitedEventHandler"),
  ConsumeInviteService: Symbol("ConsumeInviteService"),
  CreateInviteService: Symbol("CreateInviteService"),
  DefaultRoleId: Symbol("DefaultRoleId"),
} as const;
